Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-05, with the labels that each got.

#71 refactor: add custom logger
  package.json
  scripts/searchParamsCompiler/run.ts
  src/elasticSearchService.ts
  src/implementationGuides/index.ts
  src/loggerBuilder.ts
  src/searchInclusions.ts
  yarn.lock
Labels: size/m

#72 chore(release): 2.5.2
  CHANGELOG.md
  package.json
Labels: size/xs

#74 fix: use exact string matching for references
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/referenceQuery.test.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: size/s

#75 chore(release): 2.6.1
  CHANGELOG.md
  package.json
Labels: size/xs

#70 chore: adding GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s
