Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-11, with the labels that each got.

#129 feat: enable chained parameters in search
  README.md
  src/QueryBuilder/chain.test.ts
  src/QueryBuilder/chain.ts
  src/QueryBuilder/index.ts
  src/QueryBuilder/searchModifiers.ts
  src/QueryBuilder/util.test.ts
  src/QueryBuilder/util.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/constants.ts
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
Labels: size/xl

#133 chore(release): 3.8.0
  CHANGELOG.md
  package.json
Labels: size/xs

#135 chore: add git secrets scan
  .github/workflows/unit-test.yaml
Labels: size/s

#134 feat: support .extension() fn in SearchParameter expressions
  scripts/searchParamsCompiler/run.ts
  src/implementationGuides/__snapshots__/index.test.ts.snap
  src/implementationGuides/index.test.ts
  src/implementationGuides/reducedFHIRPath.ne
  src/implementationGuides/reducedFHIRPath.ts
Labels: size/s

#136 chore(release): 3.9.0
  src/implementationGuides/CHANGELOG.md
Labels: size/s

#137 chore(release): 3.9.0 - Update package.json
  package.json
Labels: size/xs

#140 chore: update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#139 fix: chained parameters with zero matches returns empty
  src/QueryBuilder/chain.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
Labels: size/m

#141 chore(release): 3.9.1
  CHANGELOG.md
  package.json
Labels: size/xs
