Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-07, with the labels that each got.

#89 feat: Add flexibility to searches against static ES mapping
  .github/workflows/unit-test.yaml
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/quantityQuery.test.ts
  src/QueryBuilder/typeQueries/quantityQuery.ts
  src/QueryBuilder/typeQueries/referenceQuery.test.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
Labels: enhancement, size/m

#90 feat: handle uris; not escaping the value
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/uriQuery.test.ts
  src/QueryBuilder/typeQueries/uriQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
Labels: enhancement, size/m

#92 chore(release): 3.1.0
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#93 feat: support OR search parameters (comma)
  src/QueryBuilder/index.ts
  src/QueryBuilder/searchOR.test.ts
  src/QueryBuilder/searchOR.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
Labels: size/m

#96 chore(release): 3.2.0
  CHANGELOG.md
  package.json
Labels: size/xs

#97 fix: handle _include refs in paths with arrays
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  src/getAllValuesForFHIRPath.test.ts
  src/getAllValuesForFHIRPath.ts
  src/searchInclusions.test.ts
  src/searchInclusions.ts
Labels: size/m
