Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-08, with the labels that each got.

#98 fix: remove duplicate Resource search params
  src/FHIRSearchParametersRegistry/index.test.ts
  src/FHIRSearchParametersRegistry/index.ts
Labels: size/s

#99 chore(release): 3.2.1
  CHANGELOG.md
  package.json
Labels: size/s

#102 feat: implement multi-tenancy
  package.json
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
  yarn.lock
Labels: size/l

#103 chore(release): 3.3.0
  CHANGELOG.md
  package.json
Labels: size/xs

#105 test: add tests for `stringQuery`s
  src/QueryBuilder/typeQueries/stringQuery.test.ts
Labels: size/s

#111 chore(release): 3.4.0
  CHANGELOG.md
  package.json
Labels: size/xs

#108 feat: add support for exact search modifier
  package.json
  src/QueryBuilder/index.ts
  src/QueryBuilder/searchModifiers.test.ts
  src/QueryBuilder/searchModifiers.ts
  src/QueryBuilder/typeQueries/dateQuery.ts
  src/QueryBuilder/typeQueries/numberQuery.ts
  src/QueryBuilder/typeQueries/quantityQuery.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
  src/QueryBuilder/typeQueries/stringQuery.test.ts
  src/QueryBuilder/typeQueries/stringQuery.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/QueryBuilder/typeQueries/uriQuery.ts
  src/elasticSearchService.ts
  yarn.lock
Labels: size/m
