Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-04, with the labels that each got.

#53 refactor: move query building code into QueryBuilder
  src/FHIRSearchParametersRegistry/index.ts
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/stringQuery.ts
  src/constants.ts
  src/elasticSearchService.ts
Labels: size/m

#54 feat: support prefixes and proper range queries for date parameters
  THIRD-PARTY
  jest.config.js
  package.json
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/dateQuery.test.ts
  src/QueryBuilder/typeQueries/dateQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  yarn.lock
Labels: size/m

#55 feat: allow milliseconds in date queries
  src/QueryBuilder/typeQueries/dateQuery.test.ts
  src/QueryBuilder/typeQueries/dateQuery.ts
Labels: size/m

#56 feat: support token parameters
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
Labels: size/m

#57 chore(release): 2.3.0
  CHANGELOG.md
  package.json
Labels: size/s

#58 feat: support number and quantity type parameters
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/common/number.test.ts
  src/QueryBuilder/typeQueries/common/number.ts
  src/QueryBuilder/typeQueries/common/prefixRange.ts
  src/QueryBuilder/typeQueries/dateQuery.ts
  src/QueryBuilder/typeQueries/numberQuery.test.ts
  src/QueryBuilder/typeQueries/numberQuery.ts
  src/QueryBuilder/typeQueries/quantityQuery.test.ts
  src/QueryBuilder/typeQueries/quantityQuery.ts
Labels: size/l

#59 chore(release): 2.4.0
  CHANGELOG.md
  package.json
Labels: size/xs

#60 feat: allow sorting by date type parameters
  src/QueryBuilder/index.ts
  src/QueryBuilder/sort.test.ts
  src/QueryBuilder/sort.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/constants.ts
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
Labels: size/m

#61 feat: support Period type fields for date params
  src/QueryBuilder/typeQueries/common/prefixRange.ts
  src/QueryBuilder/typeQueries/dateQuery.test.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: size/m

#62 feat: allow repeated search parameters
  src/QueryBuilder/index.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
Labels: size/m

#63 chore(release): 2.5.0
  CHANGELOG.md
  package.json
Labels: size/s

#66 chore: add security scanning
  .github/workflows/codeql-analysis.yml
Labels: size/s

#65 fix: token search params were matching additional documents
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: size/s

#64 fix: fix ne prefix was matching extra records
  src/QueryBuilder/typeQueries/common/prefixRange.ts
  src/QueryBuilder/typeQueries/dateQuery.test.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: size/m

#67 chore(release): 2.5.1
  CHANGELOG.md
  package.json
Labels: size/s
