Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-09, with the labels that each got.

#114 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .npmrc
  .prettierrc.js
  THIRD-PARTY
  src/constants.ts
  src/elasticSearch.ts
  src/index.ts
Labels: size/xl

#113 feat: implement ":contains" modifier
  README.md
  src/QueryBuilder/typeQueries/stringQuery.test.ts
  src/QueryBuilder/typeQueries/stringQuery.ts
Labels: size/m

#115 fix: further reference support
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/referenceQuery.test.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: bug, size/m

#116 chore(release): 3.5.0
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#117 fix: token search should be exact matches
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
Labels: bug

#118 chore(release): 3.5.1
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#119 fix: fix _id searches
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.ts
Labels: bug, size/s

#120 chore(release): 3.5.2
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#121 chore: resolve transitive dependency on set-value
  package.json
  yarn.lock
Labels: size/s

#123 fix: update IG validation to reject reference params with no target
  src/implementationGuides/__snapshots__/index.test.ts.snap
  src/implementationGuides/index.test.ts
  src/implementationGuides/index.ts
Labels: size/s
