Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2021-06, with the labels that each got.

#76 fix: Show true size for ES results
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/constants.ts
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
Labels: bug, size/s

#79 feat!: Use alias in place of index for search
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
Labels: size/m

#81 chore(release): 3.0.0
  CHANGELOG.md
  package.json
Labels: size/s

#85 feat: handle searches against static ES mapping
  .github/workflows/unit-test.yaml
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/quantityQuery.test.ts
  src/QueryBuilder/typeQueries/quantityQuery.ts
  src/QueryBuilder/typeQueries/referenceQuery.test.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
Labels: enhancement, size/m

#86 feat: handle uris; not escaping the value
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/uriQuery.test.ts
  src/QueryBuilder/typeQueries/uriQuery.ts
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
Labels: enhancement, size/m

#87 chore(release): 2.7.0
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#84 feat: implement multi-tenancy
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
Labels: size/l
