Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2022-01, with the labels that each got.

#150 refactor: consolidate parsing logic into FhirQueryParser
  src/FhirQueryParser/index.test.ts
  src/FhirQueryParser/index.ts
  src/FhirQueryParser/searchOR.test.ts
  src/FhirQueryParser/searchOR.ts
  src/FhirQueryParser/typeParsers/dateParser.test.ts
  src/FhirQueryParser/typeParsers/dateParser.ts
  src/FhirQueryParser/typeParsers/numberParser.test.ts
  src/FhirQueryParser/typeParsers/numberParser.ts
  src/FhirQueryParser/typeParsers/quantityParser.test.ts
  src/FhirQueryParser/typeParsers/quantityParser.ts
  src/FhirQueryParser/typeParsers/tokenParser.test.ts
  src/FhirQueryParser/typeParsers/tokenParser.ts
  src/FhirQueryParser/util.test.ts
  src/FhirQueryParser/util.ts
  src/QueryBuilder/chain.ts
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/dateQuery.test.ts
  src/QueryBuilder/typeQueries/dateQuery.ts
  src/QueryBuilder/typeQueries/numberQuery.test.ts
  src/QueryBuilder/typeQueries/numberQuery.ts
  src/QueryBuilder/typeQueries/quantityQuery.test.ts
  src/QueryBuilder/typeQueries/quantityQuery.ts
  src/QueryBuilder/typeQueries/tokenQuery.test.ts
  src/QueryBuilder/typeQueries/tokenQuery.ts
Labels: size/xl

#155 refactor: add chained and inclusion params to parser
  src/FhirQueryParser/index.test.ts
  src/FhirQueryParser/index.ts
  src/constants.ts
Labels: size/s

#151 chore: add logging for unsupported query params
  src/FhirQueryParser/index.ts
  src/constants.ts
Labels: size/s

#152 chore: add unit test coverage enforcement
  .github/workflows/code-coverage.yml
  codecov.yml
  jest.config.js
  package.json
Labels: size/s

#156 feat: add InMemoryMatcher with date and number matching
  src/InMemoryMatcher/index.test.ts
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/common/__snapshots__/numericComparison.test.ts.snap
  src/InMemoryMatcher/matchers/common/numericComparison.test.ts
  src/InMemoryMatcher/matchers/common/numericComparison.ts
  src/InMemoryMatcher/matchers/dateMatch.ts
  src/InMemoryMatcher/matchers/numberMatch.test.ts
  src/InMemoryMatcher/matchers/numberMatch.ts
  src/InMemoryMatcher/matchers/stringMatch.test.ts
  src/InMemoryMatcher/matchers/stringMatch.ts
Labels: size/xl

#157 feat: add quantity matcher
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/common/numericComparison.ts
  src/InMemoryMatcher/matchers/numberMatch.ts
  src/InMemoryMatcher/matchers/quantityMatch.test.ts
  src/InMemoryMatcher/matchers/quantityMatch.ts
Labels: size/m

#153 feat: add method validateSubscriptionSearchCriteria
  package.json
  src/FhirQueryParser/index.ts
  src/elasticSearchService.test.ts
  src/elasticSearchService.ts
  yarn.lock
Labels: size/s

#159 feat: add string, token, uri matchers
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/stringMatch.test.ts
  src/InMemoryMatcher/matchers/stringMatch.ts
  src/InMemoryMatcher/matchers/tokenMatch.test.ts
  src/InMemoryMatcher/matchers/tokenMatch.ts
  src/InMemoryMatcher/matchers/uriMatch.test.ts
  src/InMemoryMatcher/matchers/uriMatch.ts
Labels: size/m

#160 refactor: add referenceParser
  src/FhirQueryParser/index.ts
  src/FhirQueryParser/typeParsers/referenceParser.test.ts
  src/FhirQueryParser/typeParsers/referenceParser.ts
  src/QueryBuilder/index.ts
  src/QueryBuilder/typeQueries/referenceQuery.test.ts
  src/QueryBuilder/typeQueries/referenceQuery.ts
Labels: size/m

#161 feat: add referenceMatcher
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/referenceMatcher.test.ts
  src/InMemoryMatcher/matchers/referenceMatcher.ts
Labels: size/m

#163 feat: support modifiers in InMemoryMatcher
  src/FhirQueryParser/index.test.ts
  src/FhirQueryParser/index.ts
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/stringMatch.test.ts
  src/InMemoryMatcher/matchers/stringMatch.ts
Labels: size/m
