Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2022-02, with the labels that each got.

#164 fix: allow revinclude to return more than 10 resources
  src/__snapshots__/elasticSearchService.test.ts.snap
  src/constants.ts
  src/elasticSearchService.ts
  src/searchInclusions.ts
Labels: size/s

#165 chore(release): 3.9.3
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#168 fix: chain parameters should inspect conditions to narrow down possible target types
  src/QueryBuilder/chain.test.ts
  src/QueryBuilder/chain.ts
  src/constants.ts
Labels: size/m

#169 chore(release): 3.9.4
  CHANGELOG.md
  package.json
Labels: size/s, auto-release-pr

#162 feat: add extension.valueReference to search mappings
  scripts/elasticSearchMappingsGenerator/constants.ts
  src/schema/searchMappingsBase.3.0.1.json
  src/schema/searchMappingsBase.4.0.1.json
  src/searchMappings/__snapshots__/index.test.ts.snap
Labels: size/xl

#171 chore(release): 3.10.0
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#172 fix: actually enable token and uri matching
  src/InMemoryMatcher/index.ts
  src/InMemoryMatcher/matchers/tokenMatch.test.ts
Labels: size/s

#175 fix: update code coverage to not run on feat branches
  .github/workflows/code-coverage.yml
Labels: size/xs

#174 feat: send SNS messages for subscriptions
  package.json
  src/StreamSubscriptionMatcher/StreamSubscriptionMatcher.ts
  src/StreamSubscriptionMatcher/index.ts
  src/StreamSubscriptionMatcher/subscriptions.ts
  yarn.lock
Labels: size/l

#179 perf: Increase sockets for SNS client, add xray
  package.json
  src/StreamSubscriptionMatcher/StreamSubscriptionMatcher.ts
  yarn.lock
Labels: size/m
