Repository awslabs/fhir-works-on-aws-search-es, pull requests merged in 2023-01, with the labels that each got.

#194 chore: fix dependency version
  package.json
  yarn.lock
Labels: size/s

#193 fix: map code fields to keyword
  src/FhirQueryParser/index.ts
  src/searchMappings/__snapshots__/index.test.ts.snap
  src/searchMappings/fhirTypeToESMapping.ts
Labels: size/xl

#195 chore(release): 3.12.1
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr
